-- jev_dot_pipe.vhd -- generated by the WASMApollo EDA (heapvm vgpu apollo) from typed fabric `jev_dot_pipe`.
-- 37 LUT4 cells, 18 word PEs, 18 registers, 5 combinational levels.
-- Clocking matches the vFPGA / vASIC fabric: each rising clk edge latches every register
-- from the settled levels; rst (synchronous) loads the fabric's initial state.
-- Jev microcode ROM `route_x`: controller state -> Jev's answer -> select code (LSB first: rom_30 rom_31)
--   state  answer        p      code
--   0      x0            1.000  00
--   1      x1            1.000  01
--   2      x2            1.000  10
--   3      x3            1.000  11
-- Jev microcode ROM `route_w`: controller state -> Jev's answer -> select code (LSB first: rom_32 rom_33)
--   state  answer        p      code
--   0      w0            1.000  00
--   1      w1            1.000  01
--   2      w2            1.000  10
--   3      w3            1.000  11
-- Jev microcode ROM `mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_34)
--   state  answer        p      code
--   0      mac           1.000  1
--   1      mac           1.000  1
--   2      mac           1.000  1
--   3      mac           1.000  1

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_dot_pipe is
  port (
    clk : in std_logic;
    rst : in std_logic;
    x0 : in unsigned(31 downto 0);
    x1 : in unsigned(31 downto 0);
    x2 : in unsigned(31 downto 0);
    x3 : in unsigned(31 downto 0);
    w0 : in unsigned(31 downto 0);
    w1 : in unsigned(31 downto 0);
    w2 : in unsigned(31 downto 0);
    w3 : in unsigned(31 downto 0);
    in_valid : in std_logic;
    out_ready : in std_logic;
    in_ready : out std_logic;
    result : out unsigned(31 downto 0);
    out_valid : out std_logic
  );
end entity jev_dot_pipe;

architecture fabric of jev_dot_pipe is
  -- a LUT4 cell: row (d c b a) of truth table t
  function lut4(f_t : std_logic_vector(15 downto 0); f_d, f_c, f_b, f_a : std_logic) return std_logic is
  begin
    return f_t(to_integer(unsigned'(f_d & f_c & f_b & f_a)));
  end function;
  signal state_0 : std_logic := '0';
  signal state_1 : std_logic := '0';
  signal o_valid : std_logic := '0';
  signal o_mac : std_logic := '0';
  signal o_last : std_logic := '0';
  signal s_valid : std_logic := '0';
  signal s_mac : std_logic := '0';
  signal s_last : std_logic := '0';
  signal r_valid : std_logic := '0';
  signal o_p : unsigned(31 downto 0) := x"00000000";
  signal s_p : unsigned(31 downto 0) := x"00000000";
  signal acc : unsigned(31 downto 0) := x"00000000";
  signal res : unsigned(31 downto 0) := x"00000000";
  signal a_valid : std_logic := '0';
  signal a_mac : std_logic := '0';
  signal a_last : std_logic := '0';
  signal a_x : unsigned(31 downto 0) := x"00000000";
  signal a_w : unsigned(31 downto 0) := x"00000000";
  signal rom_30 : std_logic;
  signal rom_31 : std_logic;
  signal rom_32 : std_logic;
  signal rom_33 : std_logic;
  signal rom_34 : std_logic;
  signal xnor_35 : std_logic;
  signal xnor_36 : std_logic;
  signal nand_38 : std_logic;
  signal xor3_40 : std_logic;
  signal maj_41 : std_logic;
  signal pe3_58 : unsigned(31 downto 0);
  signal not_59 : std_logic;
  signal acc_ready_61 : std_logic;
  signal pe1_77 : unsigned(31 downto 0);
  signal k_80 : unsigned(31 downto 0);
  signal and4_37 : std_logic;
  signal and_39 : std_logic;
  signal xor3_42 : std_logic;
  signal maj_43 : std_logic;
  signal sel_47 : unsigned(31 downto 0);
  signal sel_48 : unsigned(31 downto 0);
  signal sel_51 : unsigned(31 downto 0);
  signal sel_52 : unsigned(31 downto 0);
  signal and_60 : std_logic;
  signal and_62 : std_logic;
  signal sel_78 : unsigned(31 downto 0);
  signal mux_44 : std_logic;
  signal mux_45 : std_logic;
  signal and_46 : std_logic;
  signal sel_49 : unsigned(31 downto 0);
  signal sel_53 : unsigned(31 downto 0);
  signal mux_55 : std_logic;
  signal mux_56 : std_logic;
  signal a_valid_next_57 : std_logic;
  signal and_63 : std_logic;
  signal o_take_64 : std_logic;
  signal s_take_65 : std_logic;
  signal and_79 : std_logic;
  signal sel_81 : unsigned(31 downto 0);
  signal sel_50 : unsigned(31 downto 0);
  signal sel_54 : unsigned(31 downto 0);
  signal o_valid_next_66 : std_logic;
  signal sel_67 : unsigned(31 downto 0);
  signal mux_69 : std_logic;
  signal mux_71 : std_logic;
  signal s_valid_next_73 : std_logic;
  signal sel_74 : unsigned(31 downto 0);
  signal mux_75 : std_logic;
  signal mux_76 : std_logic;
  signal sel_82 : unsigned(31 downto 0);
  signal sel_83 : unsigned(31 downto 0);
  signal r_valid_next_84 : std_logic;
  signal sel_68 : unsigned(31 downto 0);
  signal mux_70 : std_logic;
  signal mux_72 : std_logic;
begin
  -- level 0
  rom_30 <= lut4(x"AAAA", '0', '0', state_1, state_0);
  rom_31 <= lut4(x"CCCC", '0', '0', state_1, state_0);
  rom_32 <= lut4(x"AAAA", '0', '0', state_1, state_0);
  rom_33 <= lut4(x"CCCC", '0', '0', state_1, state_0);
  rom_34 <= lut4(x"FFFF", '0', '0', state_1, state_0);
  xnor_35 <= lut4(x"9999", '0', '0', '1', state_0);
  xnor_36 <= lut4(x"9999", '0', '0', '1', state_1);
  nand_38 <= lut4(x"7777", '0', '0', s_valid, a_valid);
  xor3_40 <= lut4(x"9696", '0', '0', '1', state_0);
  maj_41 <= lut4(x"E8E8", '0', '0', '1', state_0);
  pe3_58 <= resize(a_x * a_w, 32);
  not_59 <= lut4(x"5555", '0', '0', '0', s_valid);
  acc_ready_61 <= lut4(x"F7F7", '0', out_ready, r_valid, o_last);
  pe1_77 <= acc + o_p;
  k_80 <= unsigned'(x"00000000");
  -- level 1
  and4_37 <= lut4(x"8000", '1', '1', xnor_36, xnor_35);
  and_39 <= lut4(x"8888", '0', '0', nand_38, in_valid);
  xor3_42 <= lut4(x"9696", '0', maj_41, '0', state_1);
  maj_43 <= lut4(x"E8E8", '0', maj_41, '0', state_1);
  sel_47 <= x1 when rom_30 = '1' else x0;
  sel_48 <= x3 when rom_30 = '1' else x2;
  sel_51 <= w1 when rom_32 = '1' else w0;
  sel_52 <= w3 when rom_32 = '1' else w2;
  and_60 <= lut4(x"8888", '0', '0', not_59, a_valid);
  and_62 <= lut4(x"8888", '0', '0', acc_ready_61, o_valid);
  sel_78 <= pe1_77 when o_mac = '1' else acc;
  -- level 2
  mux_44 <= lut4(x"E4E4", '0', xor3_40, state_0, and_39);
  mux_45 <= lut4(x"E4E4", '0', xor3_42, state_1, and_39);
  and_46 <= lut4(x"8888", '0', '0', and4_37, and_39);
  sel_49 <= sel_48 when rom_31 = '1' else sel_47;
  sel_53 <= sel_52 when rom_33 = '1' else sel_51;
  mux_55 <= lut4(x"E4E4", '0', rom_34, a_mac, and_39);
  mux_56 <= lut4(x"E4E4", '0', and4_37, a_last, and_39);
  a_valid_next_57 <= lut4(x"EAEA", '0', s_valid, a_valid, and_39);
  and_63 <= lut4(x"8888", '0', '0', s_valid, and_62);
  o_take_64 <= lut4(x"A2A2", '0', and_62, o_valid, and_60);
  s_take_65 <= lut4(x"0808", '0', and_62, o_valid, and_60);
  and_79 <= lut4(x"8888", '0', '0', o_last, and_62);
  sel_81 <= k_80 when o_last = '1' else sel_78;
  -- level 3
  sel_50 <= sel_49 when and_39 = '1' else a_x;
  sel_54 <= sel_53 when and_39 = '1' else a_w;
  o_valid_next_66 <= lut4(x"EEFE", and_62, o_valid, o_take_64, and_63);
  sel_67 <= pe3_58 when o_take_64 = '1' else o_p;
  mux_69 <= lut4(x"E4E4", '0', a_mac, o_mac, o_take_64);
  mux_71 <= lut4(x"E4E4", '0', a_last, o_last, o_take_64);
  s_valid_next_73 <= lut4(x"AEAE", '0', and_63, s_valid, s_take_65);
  sel_74 <= pe3_58 when s_take_65 = '1' else s_p;
  mux_75 <= lut4(x"E4E4", '0', a_mac, s_mac, s_take_65);
  mux_76 <= lut4(x"E4E4", '0', a_last, s_last, s_take_65);
  sel_82 <= sel_81 when and_62 = '1' else acc;
  sel_83 <= sel_78 when and_79 = '1' else res;
  r_valid_next_84 <= lut4(x"AEAE", '0', out_ready, r_valid, and_79);
  -- level 4
  sel_68 <= s_p when and_63 = '1' else sel_67;
  mux_70 <= lut4(x"E4E4", '0', s_mac, mux_69, and_63);
  mux_72 <= lut4(x"E4E4", '0', s_last, mux_71, and_63);
  -- the clock edge
  process (clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        state_0 <= '0';
        state_1 <= '0';
        o_valid <= '0';
        o_mac <= '0';
        o_last <= '0';
        s_valid <= '0';
        s_mac <= '0';
        s_last <= '0';
        r_valid <= '0';
        o_p <= x"00000000";
        s_p <= x"00000000";
        acc <= x"00000000";
        res <= x"00000000";
        a_valid <= '0';
        a_mac <= '0';
        a_last <= '0';
        a_x <= x"00000000";
        a_w <= x"00000000";
      else
        state_0 <= mux_44;
        state_1 <= mux_45;
        o_valid <= o_valid_next_66;
        o_mac <= mux_70;
        o_last <= mux_72;
        s_valid <= s_valid_next_73;
        s_mac <= mux_75;
        s_last <= mux_76;
        r_valid <= r_valid_next_84;
        o_p <= sel_68;
        s_p <= sel_74;
        acc <= sel_82;
        res <= sel_83;
        a_valid <= a_valid_next_57;
        a_mac <= mux_55;
        a_last <= mux_56;
        a_x <= sel_50;
        a_w <= sel_54;
      end if;
    end if;
  end process;
  -- outputs
  in_ready <= and_46;
  result <= res;
  out_valid <= r_valid;
end architecture fabric;
