`timescale 1ns/1ps
// jev_dot_pipe_tb.v -- self-checking testbench generated by the WASMApollo EDA; the expected
// values are the fabric's golden model (RefSim). Run: iverilog -o tb jev_dot_pipe.v jev_dot_pipe_tb.v && vvp tb

module jev_dot_pipe_tb;
  reg clk = 1'b0;
  reg rst = 1'b1;
  reg [31:0] x0 = 0;
  reg [31:0] x1 = 0;
  reg [31:0] x2 = 0;
  reg [31:0] x3 = 0;
  reg [31:0] w0 = 0;
  reg [31:0] w1 = 0;
  reg [31:0] w2 = 0;
  reg [31:0] w3 = 0;
  reg in_valid = 0;
  reg out_ready = 0;
  wire in_ready;
  wire [31:0] result;
  wire out_valid;
  integer errors = 0;

  jev_dot_pipe dut (.clk(clk), .rst(rst), .x0(x0), .x1(x1), .x2(x2), .x3(x3), .w0(w0), .w1(w1), .w2(w2), .w3(w3), .in_valid(in_valid), .out_ready(out_ready), .in_ready(in_ready), .result(result), .out_valid(out_valid));

  always #5 clk = ~clk;
  task tick;
    begin
      @(posedge clk);
      #1;
    end
  endtask

  initial begin
    // vector 0
    x0 = 32'h0000152D;
    x1 = 32'h0000386C;
    x2 = 32'h00001EC1;
    x3 = 32'h0000103E;
    w0 = 32'h00001E47;
    w1 = 32'h00000EAD;
    w2 = 32'h0000242D;
    w3 = 32'h000033D6;
    in_valid = 1'h1;
    out_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 0: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h0D5FA838) begin $display("FAIL vector 0: result = %h, want %h", result, 32'h0D5FA838); errors = errors + 1; end
    if (out_valid !== 1'h0) begin $display("FAIL vector 0: out_valid = %h, want %h", out_valid, 1'h0); errors = errors + 1; end
    // vector 1
    x0 = 32'h00001EAA;
    x1 = 32'h000024AB;
    x2 = 32'h0000266C;
    x3 = 32'h00002C6A;
    w0 = 32'h000031DC;
    w1 = 32'h00002F0E;
    w2 = 32'h00000AD7;
    w3 = 32'h0000263A;
    in_valid = 1'h1;
    out_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 1: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h14F8932A) begin $display("FAIL vector 1: result = %h, want %h", result, 32'h14F8932A); errors = errors + 1; end
    if (out_valid !== 1'h0) begin $display("FAIL vector 1: out_valid = %h, want %h", out_valid, 1'h0); errors = errors + 1; end
    // vector 2
    x0 = 32'h00002FBA;
    x1 = 32'h00002F26;
    x2 = 32'h00002DBB;
    x3 = 32'h0000254A;
    w0 = 32'h00003D7D;
    w1 = 32'h00003058;
    w2 = 32'h000039E0;
    w3 = 32'h00003AB3;
    in_valid = 1'h1;
    out_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 2: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h27417240) begin $display("FAIL vector 2: result = %h, want %h", result, 32'h27417240); errors = errors + 1; end
    if (out_valid !== 1'h1) begin $display("FAIL vector 2: out_valid = %h, want %h", out_valid, 1'h1); errors = errors + 1; end
    // vector 3
    x0 = 32'h00003F8E;
    x1 = 32'h00003D5A;
    x2 = 32'h00003086;
    x3 = 32'h00000FD4;
    w0 = 32'h00002F5D;
    w1 = 32'h0000308A;
    w2 = 32'h00001DAD;
    w3 = 32'h00000F46;
    in_valid = 1'h0;
    out_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 3: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h00000000) begin $display("FAIL vector 3: result = %h, want %h", result, 32'h00000000); errors = errors + 1; end
    if (out_valid !== 1'h0) begin $display("FAIL vector 3: out_valid = %h, want %h", out_valid, 1'h0); errors = errors + 1; end
    // vector 4
    x0 = 32'h00002A78;
    x1 = 32'h0000293C;
    x2 = 32'h00001301;
    x3 = 32'h00003297;
    w0 = 32'h00002000;
    w1 = 32'h00001697;
    w2 = 32'h00000B36;
    w3 = 32'h000009B3;
    in_valid = 1'h1;
    out_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 4: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h0BB2362F) begin $display("FAIL vector 4: result = %h, want %h", result, 32'h0BB2362F); errors = errors + 1; end
    if (out_valid !== 1'h0) begin $display("FAIL vector 4: out_valid = %h, want %h", out_valid, 1'h0); errors = errors + 1; end
    // vector 5
    x0 = 32'h000020E7;
    x1 = 32'h000004A3;
    x2 = 32'h000027A6;
    x3 = 32'h0000192B;
    w0 = 32'h00000415;
    w1 = 32'h00002F60;
    w2 = 32'h00000081;
    w3 = 32'h00000019;
    in_valid = 1'h1;
    out_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 5: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h017868EC) begin $display("FAIL vector 5: result = %h, want %h", result, 32'h017868EC); errors = errors + 1; end
    if (out_valid !== 1'h0) begin $display("FAIL vector 5: out_valid = %h, want %h", out_valid, 1'h0); errors = errors + 1; end
    // vector 6
    x0 = 32'h0000268A;
    x1 = 32'h00003DDE;
    x2 = 32'h00002748;
    x3 = 32'h00001A07;
    w0 = 32'h0000039E;
    w1 = 32'h0000171B;
    w2 = 32'h00002B08;
    w3 = 32'h00003445;
    in_valid = 1'h1;
    out_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 6: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h120BA1B9) begin $display("FAIL vector 6: result = %h, want %h", result, 32'h120BA1B9); errors = errors + 1; end
    if (out_valid !== 1'h1) begin $display("FAIL vector 6: out_valid = %h, want %h", out_valid, 1'h1); errors = errors + 1; end
    // vector 7
    x0 = 32'h0000118F;
    x1 = 32'h00002D4B;
    x2 = 32'h00002A4F;
    x3 = 32'h000031E3;
    w0 = 32'h00001C04;
    w1 = 32'h00002637;
    w2 = 32'h00000122;
    w3 = 32'h000021F8;
    in_valid = 1'h0;
    out_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (16) tick;
    if (in_ready !== 1'h0) begin $display("FAIL vector 7: in_ready = %h, want %h", in_ready, 1'h0); errors = errors + 1; end
    if (result !== 32'h00000000) begin $display("FAIL vector 7: result = %h, want %h", result, 32'h00000000); errors = errors + 1; end
    if (out_valid !== 1'h0) begin $display("FAIL vector 7: out_valid = %h, want %h", out_valid, 1'h0); errors = errors + 1; end
    if (errors == 0) $display("PASS jev_dot_pipe: 8 vectors");
    else $display("FAIL jev_dot_pipe: %0d mismatches", errors);
    $finish;
  end
endmodule
