-- jev_dot_pipe_tb.vhd -- self-checking testbench generated by the WASMApollo EDA; the expected
-- values are the fabric's golden model (RefSim). Run: ghdl -a jev_dot_pipe.vhd jev_dot_pipe_tb.vhd && ghdl -e jev_dot_pipe_tb && ghdl -r jev_dot_pipe_tb

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_dot_pipe_tb is
end entity jev_dot_pipe_tb;

architecture sim of jev_dot_pipe_tb is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';
  signal finished : boolean := false;
  signal x0 : unsigned(31 downto 0) := (others => '0');
  signal x1 : unsigned(31 downto 0) := (others => '0');
  signal x2 : unsigned(31 downto 0) := (others => '0');
  signal x3 : unsigned(31 downto 0) := (others => '0');
  signal w0 : unsigned(31 downto 0) := (others => '0');
  signal w1 : unsigned(31 downto 0) := (others => '0');
  signal w2 : unsigned(31 downto 0) := (others => '0');
  signal w3 : unsigned(31 downto 0) := (others => '0');
  signal in_valid : std_logic := '0';
  signal out_ready : std_logic := '0';
  signal in_ready : std_logic;
  signal result : unsigned(31 downto 0);
  signal out_valid : std_logic;
begin
  dut : entity work.jev_dot_pipe port map (clk => clk, rst => rst, x0 => x0, x1 => x1, x2 => x2, x3 => x3, w0 => w0, w1 => w1, w2 => w2, w3 => w3, in_valid => in_valid, out_ready => out_ready, in_ready => in_ready, result => result, out_valid => out_valid);
  clk <= not clk after 5 ns when not finished else '0';

  check : process
    variable errors : natural := 0;
    procedure tick is
    begin
      wait until rising_edge(clk);
      wait for 1 ns;
    end procedure;
  begin
    -- vector 0
    x0 <= x"0000152D";
    x1 <= x"0000386C";
    x2 <= x"00001EC1";
    x3 <= x"0000103E";
    w0 <= x"00001E47";
    w1 <= x"00000EAD";
    w2 <= x"0000242D";
    w3 <= x"000033D6";
    in_valid <= '1';
    out_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 0: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"0D5FA838" then
      report "FAIL vector 0: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '0' then
      report "FAIL vector 0: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 1
    x0 <= x"00001EAA";
    x1 <= x"000024AB";
    x2 <= x"0000266C";
    x3 <= x"00002C6A";
    w0 <= x"000031DC";
    w1 <= x"00002F0E";
    w2 <= x"00000AD7";
    w3 <= x"0000263A";
    in_valid <= '1';
    out_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 1: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"14F8932A" then
      report "FAIL vector 1: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '0' then
      report "FAIL vector 1: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 2
    x0 <= x"00002FBA";
    x1 <= x"00002F26";
    x2 <= x"00002DBB";
    x3 <= x"0000254A";
    w0 <= x"00003D7D";
    w1 <= x"00003058";
    w2 <= x"000039E0";
    w3 <= x"00003AB3";
    in_valid <= '1';
    out_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 2: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"27417240" then
      report "FAIL vector 2: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '1' then
      report "FAIL vector 2: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 3
    x0 <= x"00003F8E";
    x1 <= x"00003D5A";
    x2 <= x"00003086";
    x3 <= x"00000FD4";
    w0 <= x"00002F5D";
    w1 <= x"0000308A";
    w2 <= x"00001DAD";
    w3 <= x"00000F46";
    in_valid <= '0';
    out_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 3: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"00000000" then
      report "FAIL vector 3: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '0' then
      report "FAIL vector 3: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 4
    x0 <= x"00002A78";
    x1 <= x"0000293C";
    x2 <= x"00001301";
    x3 <= x"00003297";
    w0 <= x"00002000";
    w1 <= x"00001697";
    w2 <= x"00000B36";
    w3 <= x"000009B3";
    in_valid <= '1';
    out_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 4: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"0BB2362F" then
      report "FAIL vector 4: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '0' then
      report "FAIL vector 4: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 5
    x0 <= x"000020E7";
    x1 <= x"000004A3";
    x2 <= x"000027A6";
    x3 <= x"0000192B";
    w0 <= x"00000415";
    w1 <= x"00002F60";
    w2 <= x"00000081";
    w3 <= x"00000019";
    in_valid <= '1';
    out_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 5: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"017868EC" then
      report "FAIL vector 5: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '0' then
      report "FAIL vector 5: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 6
    x0 <= x"0000268A";
    x1 <= x"00003DDE";
    x2 <= x"00002748";
    x3 <= x"00001A07";
    w0 <= x"0000039E";
    w1 <= x"0000171B";
    w2 <= x"00002B08";
    w3 <= x"00003445";
    in_valid <= '1';
    out_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 6: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"120BA1B9" then
      report "FAIL vector 6: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '1' then
      report "FAIL vector 6: out_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 7
    x0 <= x"0000118F";
    x1 <= x"00002D4B";
    x2 <= x"00002A4F";
    x3 <= x"000031E3";
    w0 <= x"00001C04";
    w1 <= x"00002637";
    w2 <= x"00000122";
    w3 <= x"000021F8";
    in_valid <= '0';
    out_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 16 loop
      tick;
    end loop;
    if in_ready /= '0' then
      report "FAIL vector 7: in_ready" severity error;
      errors := errors + 1;
    end if;
    if result /= x"00000000" then
      report "FAIL vector 7: result" severity error;
      errors := errors + 1;
    end if;
    if out_valid /= '0' then
      report "FAIL vector 7: out_valid" severity error;
      errors := errors + 1;
    end if;
    if errors = 0 then
      report "PASS jev_dot_pipe: 8 vectors";
    else
      report "FAIL jev_dot_pipe: " & integer'image(errors) & " mismatches" severity failure;
    end if;
    finished <= true;
    wait;
  end process;
end architecture sim;
