// jev_dot_pipe.v -- generated by the WASMApollo EDA (heapvm vgpu apollo) from typed fabric `jev_dot_pipe`.
// 37 LUT4 cells, 18 word PEs, 18 registers, 5 combinational levels.
// Clocking matches the vFPGA / vASIC fabric: each rising clk edge latches every register
// from the settled levels; rst (synchronous) loads the fabric's initial state.
// Jev microcode ROM `route_x`: controller state -> Jev's answer -> select code (LSB first: rom_30 rom_31)
//   state  answer        p      code
//   0      x0            1.000  00
//   1      x1            1.000  01
//   2      x2            1.000  10
//   3      x3            1.000  11
// Jev microcode ROM `route_w`: controller state -> Jev's answer -> select code (LSB first: rom_32 rom_33)
//   state  answer        p      code
//   0      w0            1.000  00
//   1      w1            1.000  01
//   2      w2            1.000  10
//   3      w3            1.000  11
// Jev microcode ROM `mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_34)
//   state  answer        p      code
//   0      mac           1.000  1
//   1      mac           1.000  1
//   2      mac           1.000  1
//   3      mac           1.000  1

`timescale 1ns/1ps
module jev_dot_pipe (
  input  wire        clk,
  input  wire        rst,
  input  wire [31:0] x0,
  input  wire [31:0] x1,
  input  wire [31:0] x2,
  input  wire [31:0] x3,
  input  wire [31:0] w0,
  input  wire [31:0] w1,
  input  wire [31:0] w2,
  input  wire [31:0] w3,
  input  wire in_valid,
  input  wire out_ready,
  output wire in_ready,
  output wire [31:0] result,
  output wire out_valid
);

  function lut4(input [15:0] t, input [3:0] i);  // a LUT4 cell: row i of truth table t
    lut4 = t[i];
  endfunction

  // registers
  reg state_0 = 1'h0;
  reg state_1 = 1'h0;
  reg o_valid = 1'h0;
  reg o_mac = 1'h0;
  reg o_last = 1'h0;
  reg s_valid = 1'h0;
  reg s_mac = 1'h0;
  reg s_last = 1'h0;
  reg r_valid = 1'h0;
  reg [31:0] o_p = 32'h00000000;
  reg [31:0] s_p = 32'h00000000;
  reg [31:0] acc = 32'h00000000;
  reg [31:0] res = 32'h00000000;
  reg a_valid = 1'h0;
  reg a_mac = 1'h0;
  reg a_last = 1'h0;
  reg [31:0] a_x = 32'h00000000;
  reg [31:0] a_w = 32'h00000000;

  // level 0
  wire rom_30 = lut4(16'hAAAA, {1'b0, 1'b0, state_1, state_0});
  wire rom_31 = lut4(16'hCCCC, {1'b0, 1'b0, state_1, state_0});
  wire rom_32 = lut4(16'hAAAA, {1'b0, 1'b0, state_1, state_0});
  wire rom_33 = lut4(16'hCCCC, {1'b0, 1'b0, state_1, state_0});
  wire rom_34 = lut4(16'hFFFF, {1'b0, 1'b0, state_1, state_0});
  wire xnor_35 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, state_0});
  wire xnor_36 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, state_1});
  wire nand_38 = lut4(16'h7777, {1'b0, 1'b0, s_valid, a_valid});
  wire xor3_40 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, state_0});
  wire maj_41 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, state_0});
  wire [31:0] pe3_58 = (a_x * a_w);
  wire not_59 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, s_valid});
  wire acc_ready_61 = lut4(16'hF7F7, {1'b0, out_ready, r_valid, o_last});
  wire [31:0] pe1_77 = (acc + o_p);
  wire [31:0] k_80 = 32'h00000000;

  // level 1
  wire and4_37 = lut4(16'h8000, {1'b1, 1'b1, xnor_36, xnor_35});
  wire and_39 = lut4(16'h8888, {1'b0, 1'b0, nand_38, in_valid});
  wire xor3_42 = lut4(16'h9696, {1'b0, maj_41, 1'b0, state_1});
  wire maj_43 = lut4(16'hE8E8, {1'b0, maj_41, 1'b0, state_1});
  wire [31:0] sel_47 = (rom_30 ? x1 : x0);
  wire [31:0] sel_48 = (rom_30 ? x3 : x2);
  wire [31:0] sel_51 = (rom_32 ? w1 : w0);
  wire [31:0] sel_52 = (rom_32 ? w3 : w2);
  wire and_60 = lut4(16'h8888, {1'b0, 1'b0, not_59, a_valid});
  wire and_62 = lut4(16'h8888, {1'b0, 1'b0, acc_ready_61, o_valid});
  wire [31:0] sel_78 = (o_mac ? pe1_77 : acc);

  // level 2
  wire mux_44 = lut4(16'hE4E4, {1'b0, xor3_40, state_0, and_39});
  wire mux_45 = lut4(16'hE4E4, {1'b0, xor3_42, state_1, and_39});
  wire and_46 = lut4(16'h8888, {1'b0, 1'b0, and4_37, and_39});
  wire [31:0] sel_49 = (rom_31 ? sel_48 : sel_47);
  wire [31:0] sel_53 = (rom_33 ? sel_52 : sel_51);
  wire mux_55 = lut4(16'hE4E4, {1'b0, rom_34, a_mac, and_39});
  wire mux_56 = lut4(16'hE4E4, {1'b0, and4_37, a_last, and_39});
  wire a_valid_next_57 = lut4(16'hEAEA, {1'b0, s_valid, a_valid, and_39});
  wire and_63 = lut4(16'h8888, {1'b0, 1'b0, s_valid, and_62});
  wire o_take_64 = lut4(16'hA2A2, {1'b0, and_62, o_valid, and_60});
  wire s_take_65 = lut4(16'h0808, {1'b0, and_62, o_valid, and_60});
  wire and_79 = lut4(16'h8888, {1'b0, 1'b0, o_last, and_62});
  wire [31:0] sel_81 = (o_last ? k_80 : sel_78);

  // level 3
  wire [31:0] sel_50 = (and_39 ? sel_49 : a_x);
  wire [31:0] sel_54 = (and_39 ? sel_53 : a_w);
  wire o_valid_next_66 = lut4(16'hEEFE, {and_62, o_valid, o_take_64, and_63});
  wire [31:0] sel_67 = (o_take_64 ? pe3_58 : o_p);
  wire mux_69 = lut4(16'hE4E4, {1'b0, a_mac, o_mac, o_take_64});
  wire mux_71 = lut4(16'hE4E4, {1'b0, a_last, o_last, o_take_64});
  wire s_valid_next_73 = lut4(16'hAEAE, {1'b0, and_63, s_valid, s_take_65});
  wire [31:0] sel_74 = (s_take_65 ? pe3_58 : s_p);
  wire mux_75 = lut4(16'hE4E4, {1'b0, a_mac, s_mac, s_take_65});
  wire mux_76 = lut4(16'hE4E4, {1'b0, a_last, s_last, s_take_65});
  wire [31:0] sel_82 = (and_62 ? sel_81 : acc);
  wire [31:0] sel_83 = (and_79 ? sel_78 : res);
  wire r_valid_next_84 = lut4(16'hAEAE, {1'b0, out_ready, r_valid, and_79});

  // level 4
  wire [31:0] sel_68 = (and_63 ? s_p : sel_67);
  wire mux_70 = lut4(16'hE4E4, {1'b0, s_mac, mux_69, and_63});
  wire mux_72 = lut4(16'hE4E4, {1'b0, s_last, mux_71, and_63});

  always @(posedge clk) begin
    if (rst) begin
      state_0 <= 1'h0;
      state_1 <= 1'h0;
      o_valid <= 1'h0;
      o_mac <= 1'h0;
      o_last <= 1'h0;
      s_valid <= 1'h0;
      s_mac <= 1'h0;
      s_last <= 1'h0;
      r_valid <= 1'h0;
      o_p <= 32'h00000000;
      s_p <= 32'h00000000;
      acc <= 32'h00000000;
      res <= 32'h00000000;
      a_valid <= 1'h0;
      a_mac <= 1'h0;
      a_last <= 1'h0;
      a_x <= 32'h00000000;
      a_w <= 32'h00000000;
    end else begin
      state_0 <= mux_44;
      state_1 <= mux_45;
      o_valid <= o_valid_next_66;
      o_mac <= mux_70;
      o_last <= mux_72;
      s_valid <= s_valid_next_73;
      s_mac <= mux_75;
      s_last <= mux_76;
      r_valid <= r_valid_next_84;
      o_p <= sel_68;
      s_p <= sel_74;
      acc <= sel_82;
      res <= sel_83;
      a_valid <= a_valid_next_57;
      a_mac <= mux_55;
      a_last <= mux_56;
      a_x <= sel_50;
      a_w <= sel_54;
    end
  end

  // outputs
  assign in_ready = and_46;
  assign result = res;
  assign out_valid = r_valid;
endmodule
